### ISSUE TITLE
Basic Usage example  is wrong.

### ISSUE THREAD

**Issue by nacika-ins** [stanaka/docker-mackerel-agent#17]
Basic Usage on the link below is incorrect.
https://hub.docker.com/r/mackerel/mackerel-agent/

`-e 'enable_docker_plugin=1 \`

`'` is missing.

**Comment by Songmu** [comment]
Fixed at https://github.com/stanaka/docker-mackerel-agent/commit/5151b45d94a58d0f4c77c8af55979c3014352912.
Thank you!
